language: java
jdk:
  - openjdk11

# 1
branches:
  only:
    - main

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2'

before_install:
  - openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv -in application.yml.enc -out ./src/main/resources/application.yml -d
  - openssl aes-256-cbc -K $encrypted_2e8be43b8f53_key -iv $encrypted_2e8be43b8f53_iv -in application-oauth.yml.enc -out ./src/main/resources/application-oauth.yml -d
  - chmod +x mvnw

# 3
script: "./mvnw clean package"

before_deploy:
  - zip -r recoder *
  - mkdir -p deploy
  - mv recoder.zip deploy/recoder.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: recoder-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true # master 브랜치 말고도 다른 브랜치에도 권한을 허용

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: recdoer-build # S3 버킷
    key: recoder.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: recoder # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: recoder-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true # master 브랜치 말고도 다른 브랜치에도 권한을 허용

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - hjw43ok@hs.ac.kr
