language: java
jdk:
  - openjdk11

# 1
branches:
  only:
    - main

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2'

before_install:
  - chmod +x mvnw
  - openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv -in application.yml.enc -out application.yml -d
  - openssl aes-256-cbc -K $encrypted_2e8be43b8f53_key -iv $encrypted_2e8be43b8f53_iv -in application-oauth.yml.enc -out application-oauth.yml -d

# 3
script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - hjw43ok@hs.ac.kr

