spring:
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: none # none으로 다시 바꾸기 0514
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password: hong
    driver-class-name: org.h2.Driver
  messages:
    basename:
      - messages
      - errors
logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type:
#          descriptor:
#            sql: trace
