spring:
  profiles:
   include: oauth
  jpa:
    hibernate:
      ddl-auto: none # none으로 다시 바꾸기 0412
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recoder?serverTimezone=Asia/Seoul  # recoder가 주 DB
    username: root
    password: hong
  messages:
    basename:
      - messages
      - errors
logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type:
#          descriptor:
#            sql: trace
