server:
  port: 3033

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: test
      password: test

management:
  endpoints:
    web:
      exposure:
        include: "*"


